<?php
Yii::import('zii.widgets.CPortlet');

class Social extends CPortlet {

    public $_title = 'Tags';

    protected function renderContent() {
        return;
        ?>
        <div class="right-socical">
            <iframe style="float:left; height:63px; border:none; overflow:hidden;" src="http://www.facebook.com/plugins/like.php?app_id=141440452603597&amp;href=http://www.floatingsocialmediabuttons.com/&amp;send=false&amp;show_faces=false&amp;layout=box_count&amp;action=like&amp;colorscheme=light&amp;locale=en_US" scrolling="no" frameborder="0" allowtransparency="true"></iframe>
            <div id="gplusB" style="float:left; margin-top: 10px"><script type="text/javascript" src="http://apis.google.com/js/plusone.js" gapi_processed="true"></script><div id="___plusone_2" style="text-indent: 0px; margin: 0px; padding: 0px; background-color: transparent; border-style: none; float: none; line-height: normal; font-size: 1px; vertical-align: baseline; display: inline-block; width: 50px; height: 60px; background-position: initial initial; background-repeat: initial initial;"><iframe frameborder="0" hspace="0" marginheight="0" marginwidth="0" scrolling="no" style="position: static; top: 0px; width: 50px; margin: 0px; border-style: none; left: 0px; visibility: visible; height: 60px;" tabindex="0" vspace="0" width="100%" id="I0_1389580723777" name="I0_1389580723777" src="https://apis.google.com/u/0/_/+1/fastbutton?usegapi=1&amp;bsv=o&amp;size=tall&amp;origin=http%3A%2F%2Ffloatingsocialmediabuttons.com&amp;url=http%3A%2F%2Fwww.floatingsocialmediabuttons.com%2F&amp;gsrc=3p&amp;ic=1&amp;jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.vi.m1yV17o2uFw.O%2Fm%3D__features__%2Fam%3DIQ%2Frt%3Dj%2Fd%3D1%2Frs%3DAItRSTP-16Fszi3ivn-L5AYHzSP_38CG4Q#_methods=onPlusOne%2C_ready%2C_close%2C_open%2C_resizeMe%2C_renderstart%2Concircled%2Cdrefresh%2Cerefresh&amp;id=I0_1389580723777&amp;parent=http%3A%2F%2Ffloatingsocialmediabuttons.com&amp;pfname=&amp;rpctoken=24733787" data-gapiattached="true" title="+1"></iframe></div></div>
            <div id="twB" style="float:left; margin-top: 10px"><iframe id="twitter-widget-2" scrolling="no" frameborder="0" allowtransparency="true" src="http://platform.twitter.com/widgets/tweet_button.1387492107.html#_=1389580724484&amp;count=vertical&amp;id=twitter-widget-2&amp;lang=en&amp;original_referer=http%3A%2F%2Ffloatingsocialmediabuttons.com%2F&amp;size=m&amp;text=FLOATING%20SOCIAL%20MEDIA%20BUTTONS&amp;url=http%3A%2F%2Fwww.floatingsocialmediabuttons.com%2F" class="twitter-share-button twitter-tweet-button twitter-count-vertical" title="Twitter Tweet Button" data-twttr-rendered="true" style="width: 59px; height: 62px;"></iframe><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script></div>
            <div id="linB" style="float:left; margin-top: 10px"><script type="text/javascript" src="http://platform.linkedin.com/in.js"></script><span class="IN-widget" style="line-height: 1; vertical-align: baseline; display: inline-block; text-align: center;"><span style="padding: 0px !important; margin: 0px !important; text-indent: 0px !important; display: inline-block !important; vertical-align: baseline !important; font-size: 1px !important;"><span id="li_ui_li_gen_1389580724239_5-container" class="IN-top"><span id="li_ui_li_gen_1389580724239_5" class="IN-top"><span id="li_ui_li_gen_1389580724239_5-inner" class="IN-top"><span id="li_ui_li_gen_1389580724239_5-content" class="IN-top">9</span></span></span></span></span><br><span style="padding: 0px !important; margin: 0px !important; text-indent: 0px !important; display: inline-block !important; vertical-align: baseline !important; font-size: 1px !important;"><span id="li_ui_li_gen_1389580724233_4"><a id="li_ui_li_gen_1389580724233_4-link" href="javascript:void(0);"><span id="li_ui_li_gen_1389580724233_4-logo">in</span><span id="li_ui_li_gen_1389580724233_4-title"><span id="li_ui_li_gen_1389580724233_4-mark"></span><span id="li_ui_li_gen_1389580724233_4-title-text">Share</span></span></a></span></span></span><script type="in/share+init" data-counter="top" data-url="http://www.floatingsocialmediabuttons.com/"></script></div>
        </div>
        <?php
    }

}
